server:
  port: 8092

spring:
  application:
    name: API-GATEWAY

  cloud:                #Gateway Configuration
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
           - Path=/users/**
          filters:            #fallBack Method configuration using circuit breaker
            - name: CircuitBreaker
              arges:
                - name: USER-SERVICE
                  fallbacuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
           - Path=/departments/**
          filters:
            - name: CircuitBreaker
              arges:
                - name: DEPARTMENT-SERVICE
                  fallbacuri: forward:/departmentServiceFallBack

  # Hystrix configuration

  hystrix:
    command:
      fallbackcmd:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 4000  #4 seconds

 # configuration for Actuator

 management:
   endpoints:
     web:
       exposure:
         include: hystrix.stream

#Api gateway Register with Eureka server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


